# Generated by Django 5.0.6 on 2024-09-15 17:27

import app.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=3, verbose_name='Tipo de documento')),
                ('numero_documento', models.PositiveIntegerField(unique=True, validators=[app.models.Administrador.validar_numero_documento], verbose_name='Número de documento')),
                ('telefono', models.PositiveIntegerField(verbose_name='Teléfono')),
                ('contrasena', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Contraseña')),
                ('conf_contrasena', models.CharField(default='', max_length=128, verbose_name='Confirmación de contraseña')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administrador', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrador',
                'verbose_name_plural': 'Administradores',
                'db_table': 'administrador',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería'), ('PSP', 'Pasaporte')], default='CC', max_length=3, verbose_name='Tipo de documento')),
                ('numero_documento', models.PositiveIntegerField(unique=True, validators=[app.models.Empleado.validar_numero_documento], verbose_name='Número de documento')),
                ('telefono', models.PositiveIntegerField(verbose_name='Teléfono')),
                ('contrasena', models.CharField(max_length=128, validators=[django.core.validators.MinLengthValidator(8)], verbose_name='Contraseña')),
                ('conf_contrasena', models.CharField(default='', max_length=128, verbose_name='Confirmación de contraseña')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='empleado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleado',
            },
        ),
    ]
