# Generated by Django 5.0.6 on 2024-09-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_empleado_telefono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='nombre',
        ),
    ]
