# Generated by Django 5.0.6 on 2024-10-02 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_administrador_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='activado',
            field=models.BooleanField(default=True, verbose_name='Activado'),
        ),
        migrations.AlterField(
            model_name='administrador',
            name='numero_documento',
            field=models.PositiveIntegerField(unique=True, verbose_name='Número de documento'),
        ),
    ]
