# Generated by Django 5.0.6 on 2024-10-02 19:05

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_administrador_activado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='activado',
            field=models.BooleanField(default=True, verbose_name='Activado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='numero_documento',
            field=models.PositiveBigIntegerField(unique=True, validators=[app.models.Empleado.validar_numero_documento], verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=10, validators=[app.models.Empleado.validar_telefono], verbose_name='Teléfono'),
        ),
    ]
