# Generated by Django 4.1.3 on 2024-07-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0005_delete_producto_alter_marca_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='marca',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
