# Generated by Django 4.1.3 on 2024-07-24 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0010_rename_unida_medida_producto_unidad_medida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
    ]
