# Generated by Django 4.1.3 on 2024-08-01 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0012_producto_unidad_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='libreria.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='libreria.marca', verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='libreria.presentacion', verbose_name='Presentacion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad_medida',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='libreria.unidadmedida', verbose_name='UnidadMedida'),
        ),
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='libreria.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='marca',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='libreria.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='libreria.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='libreria.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_medida', to='libreria.estado', verbose_name='Estado'),
        ),
    ]
