# Generated by Django 4.1.3 on 2024-08-01 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0013_estado_alter_producto_categoria_alter_producto_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estado',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
