# Generated by Django 4.1.3 on 2024-08-01 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0014_alter_estado_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='estado',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
