# Generated by Django 4.1.3 on 2024-08-01 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0015_alter_categoria_id_alter_estado_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='libreria.estado', verbose_name='Categoria'),
        ),
    ]
