# Generated by Django 4.1.3 on 2024-08-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0017_alter_categoria_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marca',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='presentacion',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='unidadmedida',
            name='estado',
        ),
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='libreria.estado', verbose_name='Categoria'),
        ),
    ]
