# Generated by Django 4.1.3 on 2024-08-01 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0018_remove_marca_estado_remove_presentacion_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marca',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marcas', to='libreria.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='presentacion',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='libreria.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='libreria.estado', verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='estado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unidades_medida', to='libreria.estado', verbose_name='Estado'),
        ),
    ]
