# Generated by Django 5.0.7 on 2024-08-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0021_producto_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='activado',
            field=models.BooleanField(default=True),
        ),
    ]
