# Generated by Django 5.0.7 on 2024-08-12 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0022_categoria_activado'),
    ]

    operations = [
        migrations.DeleteModel(
            name='libro',
        ),
    ]
