# Generated by Django 5.0.7 on 2024-08-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0024_marca_activado'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentacion',
            name='activado',
            field=models.BooleanField(default=True),
        ),
    ]
