# Generated by Django 5.0.7 on 2024-08-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0025_presentacion_activado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='activo',
            new_name='activado',
        ),
        migrations.AddField(
            model_name='unidadmedida',
            name='activado',
            field=models.BooleanField(default=True),
        ),
    ]
