# Generated by Django 5.0.7 on 2024-08-13 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0026_rename_activo_producto_activado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaingreso', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('valorunitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valortotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='persona',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='', max_length=100)),
                ('tipodocumento', models.CharField(blank=True, choices=[('cedula de ciudadania', 'Cedula de ciudadania'), ('cedula extranjera', 'Cedula extranjera'), ('tarjeta de identidad', 'Tarjeta de identidad')], default='cedula de ciudadania', max_length=100, null=True, verbose_name='tipo de documento')),
                ('rol', models.CharField(blank=True, choices=[('admin', 'Admin'), ('empleado', 'Empleado')], default='Empleado', max_length=100, null=True)),
                ('estado', models.CharField(blank=True, choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='Activo', max_length=100, null=True)),
                ('numerodocumento', models.IntegerField(default=0, verbose_name='numero de documento')),
                ('numerocelular', models.IntegerField(default=0, verbose_name='numero de celular')),
            ],
        ),
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreproducto', models.CharField(max_length=100)),
                ('fechaventa', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('valorunitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('valortotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
            ],
        ),
    ]
