# Generated by Django 5.0.6 on 2024-09-12 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0030_remove_persona_estado_remove_venta_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('numero_celular', models.BigIntegerField(verbose_name='Número de Celular')),
                ('correo_electronico', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('activado', models.BooleanField(default=True)),
                ('marca', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='libreria.marca', verbose_name='Nombre de marca')),
            ],
        ),
        migrations.CreateModel(
            name='Respaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('tamano', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='persona',
        ),
    ]
