# Generated by Django 5.0.7 on 2024-09-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0031_proveedor_respaldo_delete_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='libreria.proveedor', verbose_name='Proveedor'),
        ),
    ]
