# Generated by Django 5.1 on 2024-10-09 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0032_producto_proveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='nombreproducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.producto'),
        ),
    ]
