# Generated by Django 5.1 on 2024-10-09 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0033_alter_compra_nombreproducto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='nombreproducto',
            field=models.CharField(max_length=100),
        ),
    ]
