# Generated by Django 5.1 on 2024-10-09 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0034_alter_compra_nombreproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libreria.producto')),
            ],
        ),
    ]
