# Generated by Django 5.1 on 2024-10-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libreria', '0035_productocompra'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductoCompra',
        ),
    ]
